### ISSUE TITLE
牛哇 牛哇

### ISSUE THREAD

**Issue by wsdydeni** [yyds-zy/_ncnn#1]

**Comment by wsdydeni** [comment]
看了大佬的库，历程很相似，感同身受。

**Comment by yyds-zy** [comment]
> 看了大佬的库，历程很相似，感同身受。

现在搞ncnn模型加载了    开始大模型推理加载了  哈哈

**Comment by wsdydeni** [comment]
大佬，你的图片检测方向是横向，我怎么改成竖向的

**Comment by yyds-zy** [comment]
> 大佬，你的图片检测方向是横向，我怎么改成竖向的

修改EngineWrapper.getInstance().detect();函数中的形参ori。可以配置成动态的。等我后期在加。

**Comment by wsdydeni** [comment]
> > 大佬，你的图片检测方向是横向，我怎么改成竖向的
> 
> 修改EngineWrapper.getInstance().detect();函数中的形参ori。可以配置成动态的。等我后期在加。

早就试过了，不行。要在C++检测里面改，但是我不太会。
